apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: btci56t60-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:20c50ae4000abbe8e5b018e5ff691f3495ffb15c@sha256:0c697b09fc74abb7c91ad0ff9ba17c73e0843a7516c30e78b90787acb86fb656
          name: container-image
